sudo: required
language: python
python:
  - "3.7"
services:
  - docker

env:
  global:
    - DOCKER_IMAGE=chotuve-grupo10/chotuve-application-server:$TRAVIS_BUILD_NUMBER
    - HEROKU_DOCKER_IMAGE=registry.heroku.com/$HEROKU_APP_NAME/web

install:
  - pip install -r requirements.txt

script:
  - python -m pytest
  - pylint app_server
  - pylint tests/test_app_server.py
  - docker build -t $DOCKER_IMAGE .

before_deploy:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - docker tag $DOCKER_IMAGE $HEROKU_DOCKER_IMAGE
  - docker push $HEROKU_DOCKER_IMAGE

deploy:
  provider: script
  script: heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch:
      - master
      - dev
