version: '3'
services: 
  app:
    image: auth-server
    build: . 
    container_name: $DOCKER_IMAGE
    environment:
      - FLASK_APP=auth_server
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 8080:5000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
