version: '3'
services: 
  app:
    build: . 
    container_name: auth-server
    environment:
      - FLASK_APP=auth_server
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 8000:8000
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
