version: '3'
services: 
  app:
    image: $DOCKER_IMAGE
    build: .
    container_name: auth-server
    # environment:
      # - FLASK_APP=auth_server
      # - FLASK_ENV=development
      # - FLASK_RUN_HOST=0.0.0.0
      # - GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
